### ISSUE TITLE
LibreElec 11.0 / Nexus - globalvars.py

### ISSUE THREAD

**Issue by ojaksch** [phoerious/massengeschmack-xbmc#20]
Moin!
Ich komme aus dem [MG-Forum](https://forum.massengeschmack.tv/t/massengeschmacktv-kodi-add-on/26302/) (Die_Medienmaeuse) und habe heute einmal der besseren Wartbarkeit halber eine frische Testkiste aufgesetzt und Dein Repo geforkt. Soweit alles prima, aber zumindest unter LibreElec 11.0 muss ich der **globalvars.py** wieder ein ```import xbmc``` hinzufügen

```
import xbmcaddon
import xbmc
import xbmcvfs
import urllib.parse
```

sonst bekomme beim Aktivieren des Plugins das altbekannte

> 2023-03-14 11:39:59.610 T:5818    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'xbmc' is not defined
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.massengeschmack/default.py", line 46, in <module>
                                                       listing.show()
                                                     File "/storage/.kodi/addons/plugin.video.massengeschmack/resources/lib/listing.py", line 59, in show
                                                       self.setViewMode(self.__source.getViewMode())
                                                     File "/storage/.kodi/addons/plugin.video.massengeschmack/resources/lib/listing.py", line 73, in setViewMode
                                                       xbmc.executebuiltin('Container.SetViewMode(' + str(id) + ')')
                                                       ^^^^
                                                   NameError: name 'xbmc' is not defined
                                                   -->End of Python script error report<--
                                                   
2023-03-14 11:39:59.684 T:5817    error <general>: GetDirectory - Error getting plugin://plugin.video.massengeschmack/

**Comment by phoerious** [comment]
Es sollte irgendwo ein Deprecation-Log geben, wo drin steht, wie man von der alten auf die neue API migriert. Wenn du Rückwärtskompatibilität brauchst, kannst du zur Not auch den ModuleImportError oder NameError abfangen.

**Comment by ojaksch** [comment]
...gerade mal ein grep auf meine installierten und aktuellen Plugins gemacht, und siehe da, viele verwenden auch ein ```import xbmc```, auch gerne zusammen mit ```import xbmcvfs```, also kann es sooo deprecated nicht sein ;)

**Comment by phoerious** [comment]
Such dir ne Versionsnnummer aus. ;-)

**Comment by ojaksch** [comment]
Untertänigsten Dank! Ich wähle dann mal ... 🎲 ... die 2.7.0   Konnte auch keine weiteren Versionen oder Forks mehr auftreiben, die eine andere oder höhere Versionsnummer halten.
Push bereite ich vor. Allmählich lösen sich auch die Probleme der User auf. Mir deucht, dass dort noch irgendwelche Altlasten schlummern und Probleme machen, denn nach einem frischen Setup von Kodi und den Plugins rennt auch Dein Plugin wohl einwandfrei.
Fehlt eigentlich nur noch ein Test und Android. Wenn mir keiner zuvorkommt, mache ich das am Wochenende selber. Ich wüsste aber nicht, warum das nicht funktionieren sollte.

**Comment by ojaksch** [comment]
Jup, vorhin wegen drohender Langeweile mein Android mit einem frischen Kodi versehen, Plugin drauf und konfiguriert, läuft. Daher ein zunächst letzter PR mit der Bitte um ein neues Release.
Demnächst dann wieder mehr, wenn neue Formate dazukommen...

**Comment by phoerious** [comment]
Als Release am besten erst mal das ZIP aus dem Repository nehmen. Weiß gerade nicht, ob ich das Add-on noch in das offizielle Plugin-Repository bekomme.

**Comment by ojaksch** [comment]
Hm, von meiner Seite aus kein Thema. Aber klappt das denn dann noch in Kodi mit "...als ZIP installieren", wenn das ZIP _massengeschmack-xbmc-master.zip_ heißt? Ich meine, ich weiß gerade gar nicht, woher Kodi den Verzeichnisnamen des Plugins herholt: Vom Namen der ZIP-Datei oder aus addon.xml (was mir sinnvoller erscheint).

Als offizielles Plugin-Repo hat ja erst einmal keine Eile. Die meisten Kodi-Seiten sind ja gerade eh dicht wegen des Cybercybercyber-Einbruchs und wenn sich die Wogen gelegt haben, ich habe einen kurzen Draht zu Hias :)

**Comment by phoerious** [comment]
Das sollte eigentlich egal sein. Der Plugin-Name sollte aus der XML-Datei stammen.

**Comment by ojaksch** [comment]
...ich hätte es ja auch mal ausprobieren können, nech'? ;) Gerade nachgeholt, ja, Name des ZIPs ist Wurscht. Wird ganz normal installiert und läuft.
Sollen wir _dieses_ Ticket erst einmal schließen? Soweit sind wir ja nun mit allem durch...
