### ISSUE TITLE
Does not work in Kodi 18 Master

### ISSUE THREAD

**Issue by mase76** [phoerious/massengeschmack-xbmc#7]
Hi!
I am getting this error when trying to browse with the Massengeschmack addon on my Debian
Stretch machine with Kodi 18 Master:

`01:59:01.348 T:139685992642304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: time data 'Thu, 13 Jul 2017 20:00:00' does not match format '%a, %d %b %Y %H:%M:%S'
                                            Traceback (most recent call last):
                                              File "/home/mase/.kodi/addons/plugin.video.massengeschmack/default.py", line 45, in <module>
                                                if listing.generate(datasource):
                                              File "/home/mase/.kodi/addons/plugin.video.massengeschmack/resources/lib/listing.py", line 46, in generate
                                                for i in items:
                                              File "/home/mase/.kodi/addons/plugin.video.massengeschmack/resources/lib/datasource.py", line 302, in getListItems
                                                'premiered' : resources.lib.parseUTCDateString(i['pubdate']).strftime('%Y-%m-%d'),
                                              File "/home/mase/.kodi/addons/plugin.video.massengeschmack/resources/lib/__init__.py", line 324, in parseUTCDateString
                                                date = datetime.strptime(datestr[:-6], format)
                                              File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
                                                (data_string, format))
                                            ValueError: time data 'Thu, 13 Jul 2017 20:00:00' does not match format '%a, %d %b %Y %H:%M:%S'
                                            -->End of Python script error report<--
01:59:01.443 T:139688306874752   ERROR: GetDirectory - Error getting plugin://plugin.video.massengeschmack/?cmd=list&module=main
01:59:01.445 T:139688306874752   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.massengeschmack/?cmd=list&module=main) failed
02:00:59.435 T:139685875668736   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: time data 'Tue, 08 Nov 2016 20:00:00' does not match format '%a, %d %b %Y %H:%M:%S'
                                            Traceback (most recent call last):
                                              File "/home/mase/.kodi/addons/plugin.video.massengeschmack/default.py", line 45, in <module>
                                                if listing.generate(datasource):
                                              File "/home/mase/.kodi/addons/plugin.video.massengeschmack/resources/lib/listing.py", line 46, in generate
                                                for i in items:
                                              File "/home/mase/.kodi/addons/plugin.video.massengeschmack/resources/lib/datasource.py", line 302, in getListItems
                                                'premiered' : resources.lib.parseUTCDateString(i['pubdate']).strftime('%Y-%m-%d'),
                                              File "/home/mase/.kodi/addons/plugin.video.massengeschmack/resources/lib/__init__.py", line 326, in parseUTCDateString
                                                date = datetime(*(time.strptime(datestr[:-6], format)[0:6]))
                                              File "/usr/lib/python2.7/_strptime.py", line 478, in _strptime_time
                                                return _strptime(data_string, format)[0]
                                              File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
                                                (data_string, format))
                                            ValueError: time data 'Tue, 08 Nov 2016 20:00:00' does not match format '%a, %d %b %Y %H:%M:%S'
                                            -->End of Python script error report<--
02:00:59.857 T:139688306874752   ERROR: GetDirectory - Error getting plugin://plugin.video.massengeschmack/?cmd=list&module=jung
02:00:59.859 T:139688306874752   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.massengeschmack/?cmd=list&module=jung) failed`

I wonder, the date format seems correct.

**Comment by mase76** [comment]
My locale settings seem not to recognized.

**Comment by phoerious** [comment]
Did it work with previous versions on your machine?

**Comment by mase76** [comment]
The current version runs on Libreelec with Kodi 18 Master without problems.
The problem is on all my self built Debian Stretch machines.
It is a locale problem. I added the line
datestr = 'Sa, 22 Jul 2017 16:00:00 +0200'
to the function def parseUTCDateString(datestr):
to workaround this. The addon is usable again, except the release date is the
date I overwrote. A German date is expected, but In my system the addon
gets the UTC date. I don't know, if this is a Kodi or Debian specific problem.
Even when setting LC_ALL = de_DE.UTF-8, is makes no difference. It seems,
that I am alone with this problem.

**Comment by phoerious** [comment]
Must be a Kodi issue. The locale setting should be propagated properly to the plugin interpreter.

**Comment by mase76** [comment]
I don't know why, but it runs again.

**Comment by phoerious** [comment]
Great!

**Comment by phoerious** [comment]
I suppose I have to set the locale explicitly before parsing. I'll have to test this (but wouldn't mind if someone else made a patch).

**Comment by mase76** [comment]
Can you also reproduce this error?

**Comment by phoerious** [comment]
Not right now. Need to test it when I'm back home beginning of next year.

**Comment by mase76** [comment]
I changed the title of this issue to a better one.
